---
license: Apache-2.0
name: bomshell
creator:
 person: Chainguard, Inc
 tool: bom

artifacts:
  - type: directory
    source: ../
    license: Apache-2.0
    gomodules: true

  - type: file
    source: bomshell-windows-amd64.exe
    license: Apache-2.0
    gomodules: true

  - type: file
    source: bomshell-darwin-arm64
    license: Apache-2.0
    gomodules: true

  - type: file
    source: bomshell-darwin-amd64
    license: Apache-2.0
    gomodules: true

  - type: file
    source: bomshell-linux-amd64
    license: Apache-2.0
    gomodules: true

  - type: file
    source: bomshell-linux-arm64
    license: Apache-2.0
    gomodules: true

  - type: file
    source: bomshell-linux-arm
    license: Apache-2.0
    gomodules: true




