project_name: bomshell

env:
  - GO111MODULE=on
  - COSIGN_YES=true

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

builds:
  - id: binaries
    binary: bomshell-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: linux
        goarch: ppc64le
      - goos: linux
        goarch: s390x
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0

signs:
  - id: sbom
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: sbom

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}'

sboms:
  - documents:
      - "{{ .ProjectName }}-{{ .Version }}.spdx.json"
    cmd: bom
    args: ["generate", "-c", "../.bom.yaml", "-o", "{{ .ProjectName }}-{{ .Version }}.spdx.json", "--format=json"]
    artifacts: source

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: "SHA256SUMS"

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow
  draft: false # allow for manual edits
